# syntax=docker/dockerfile:1.7

FROM node@sha256:0353e48e0e8a993db87b720c242f54b207059d1bcc0106534896e8a11054c837 AS source-ui
ARG ALLOY_SOURCE_REF=6012ec4ac6a541ade720777ecec2f2b02b496def
RUN git clone --filter=blob:none --no-checkout https://github.com/grafana/alloy.git /src/alloy \
    && git -C /src/alloy checkout --detach "$ALLOY_SOURCE_REF" \
    && test "$(git -C /src/alloy rev-parse HEAD)" = "$ALLOY_SOURCE_REF"
WORKDIR /src/alloy/internal/web/ui
RUN --mount=type=cache,target=/root/.npm,sharing=locked npm ci --ignore-scripts --no-audit --no-fund \
    && npm run build

FROM golang@sha256:116d58cbd88c1297624acc6e967a060012422bacf9930927e23fb719189c6f36 AS moby-backport
ARG MOBY_LEGACY_REF=89c5e8fd66634b6128fc4c0e6f1236e2540e46e0
ENV PATH=/usr/local/go/bin:/usr/local/bin:/usr/bin:/bin
RUN git clone --filter=blob:none --no-checkout https://github.com/moby/moby.git /src/docker \
    && git -C /src/docker checkout --detach "$MOBY_LEGACY_REF" \
    && test "$(git -C /src/docker rev-parse HEAD)" = "$MOBY_LEGACY_REF"
COPY deploy/alloy/patches/moby-cve-2026-34040.patch /tmp/moby-cve-2026-34040.patch
RUN echo "2445c60b47a5f43b0b9ed5d25f19ae351fc63ab932a52f460d2ee23d4a893e37  /tmp/moby-cve-2026-34040.patch" | sha256sum -c - \
    && git -C /src/docker apply --check /tmp/moby-cve-2026-34040.patch \
    && git -C /src/docker apply /tmp/moby-cve-2026-34040.patch \
    && cd /src/docker \
    && go mod init github.com/docker/docker \
    && grep -Fq 'request body too large for authorization plugin' pkg/authorization/authz.go

FROM golang@sha256:116d58cbd88c1297624acc6e967a060012422bacf9930927e23fb719189c6f36 AS patched-go

FROM grafana/alloy-build-image@sha256:4371598809230ffd7611367ba0dcb92bbc8b74bda88471293e5d478b48a0d186 AS build
ARG ALLOY_SOURCE_REF=6012ec4ac6a541ade720777ecec2f2b02b496def
ARG ALLOY_VERSION=v1.18.1-sentinel.2
COPY --from=patched-go /usr/local/go /usr/local/go
COPY --from=source-ui /src/alloy /src/alloy
COPY --from=moby-backport /src/docker /src/docker
WORKDIR /src/alloy
RUN --mount=type=cache,target=/go/pkg/mod,sharing=locked \
    go mod edit -replace github.com/docker/docker=/src/docker \
    && go get github.com/apache/thrift@v0.24.0 \
           github.com/go-git/go-git/v5@v5.19.2 \
           golang.org/x/mod@v0.40.0 \
           google.golang.org/grpc@v1.83.1 \
    && go mod tidy \
    && go mod edit -require=github.com/docker/docker@v29.3.1+incompatible \
    && go mod edit -modfile=collector/go.mod -replace github.com/docker/docker=/src/docker \
    && go mod edit -modfile=collector/go.mod -require=github.com/docker/docker@v29.3.1+incompatible \
    && go mod edit -modfile=collector/go.mod -require=google.golang.org/grpc@v1.83.1 \
    && sed -i '\#  - github.com/grafana/alloy/syntax => ../syntax#a\  - github.com/docker/docker => /src/docker' collector/builder-config.yaml
RUN --mount=type=cache,target=/root/.cache/go-build,sharing=locked \
    --mount=type=cache,target=/go/pkg/mod,sharing=locked \
    RELEASE_BUILD=1 VERSION="$ALLOY_VERSION" GO_TAGS="netgo embedalloyui promtail_journal_enabled" SKIP_UI_BUILD=1 make alloy \
    && ./build/alloy --version \
    && go version -m ./build/alloy | grep -F 'go1.26.6'

FROM mirror.gcr.io/grafana/alloy@sha256:0f4434c92b3e6cdac38bb129b344e1790c246f7b6e2eaffcc16a5fa363240e33
ARG ALLOY_SOURCE_REF=6012ec4ac6a541ade720777ecec2f2b02b496def
LABEL org.opencontainers.image.source="https://github.com/grafana/alloy" \
      org.opencontainers.image.revision="$ALLOY_SOURCE_REF" \
      org.opencontainers.image.version="v1.18.1-sentinel.2" \
      io.sentinelops.moby.backport="v28.5.2+e89edb19ad7de0407a5d31e3111cb01aa10b5a38" \
      org.opencontainers.image.description="SentinelOps rebuild of Alloy v1.18.1 with patched Go, Moby and gRPC dependencies"
COPY --from=build --chown=473:473 /src/alloy/build/alloy /bin/alloy
USER 473:473
