{{- if .Values.migration.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sentinelops.fullname" . }}-migrate
  labels:
    {{- include "sentinelops.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-2"
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-20"
automountServiceAccountToken: false
{{- end }}
