{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sentinelops.serviceAccountName" . }}
  labels: {{- include "sentinelops.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: false
{{- end }}

