import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Activity, AppWindow, Beaker, BookOpen, Boxes, ChevronRight, CircleCheck, Gauge, Languages, LogOut, Moon, RadioTower, Rocket, Search, Server, ShieldCheck, Sun, TriangleAlert } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { UserManager } from 'oidc-client-ts'
import { Agent, API, Scenario, Service } from './api'

type Page = 'overview' | 'catalog' | 'tests' | 'releases' | 'agents' | 'help'
const glossary = [
  ['Availability', 'Percentual de tentativas concluídas com sucesso.'], ['Latency p95', '95% das respostas terminam abaixo desse valor.'],
  ['Error rate', 'Proporção de operações que falham.'], ['Throughput', 'Quantidade de trabalho concluído por unidade de tempo.'],
  ['SLO', 'Meta explícita de confiabilidade em uma janela.'], ['Error budget', 'Falha tolerável antes de colocar o SLO em risco.'],
  ['Burn rate', 'Velocidade de consumo do error budget.'], ['Baseline', 'Período ou versão usada como referência.'],
]

export default function App() {
  const { t, i18n } = useTranslation(); const [token, setToken] = useState(() => sessionStorage.getItem('sentinel-token') || '')
  const api = useMemo(() => new API(token), [token]); const oidc=useMemo(()=>oidcManager(),[]); const [page, setPage] = useState<Page>('overview'); const [theme, setTheme] = useState(() => localStorage.getItem('sentinel-theme') || 'dark')
  const [services, setServices] = useState<Service[]>([]); const [agents, setAgents] = useState<Agent[]>([]); const [scenarios, setScenarios] = useState<Scenario[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('sentinel-theme', theme) }, [theme])
  useEffect(()=>{if(token||!oidc||!new URLSearchParams(location.search).has('code'))return;oidc.signinRedirectCallback().then(user=>{history.replaceState({},document.title,location.pathname);sessionStorage.setItem('sentinel-token',user.access_token);setToken(user.access_token)}).catch(e=>setError(String(e)))},[oidc,token])
  useEffect(() => { if (!token) return; setLoading(true); Promise.all([api.services(), api.agents(), api.scenarios()]).then(([s,a,sc]) => { setServices(s); setAgents(a); setScenarios(sc); setError('') }).catch(e => setError(String(e))).finally(() => setLoading(false)) }, [api, token])
  if (!token) return <Login api={api} oidc={oidc} onLogin={value => { sessionStorage.setItem('sentinel-token', value); setToken(value) }} />
  const nav: [Page, string, typeof Gauge][] = [['overview', t('overview'), Gauge], ['catalog', t('catalog'), Boxes], ['tests', t('tests'), Beaker], ['releases', t('releases'), Rocket], ['agents', t('agents'), RadioTower], ['help', t('help'), BookOpen]]
  const logout = () => { sessionStorage.removeItem('sentinel-token'); setToken('');if(oidc)void oidc.signoutRedirect() }
  return <div className="shell">
    <aside className="sidebar"><div className="brand"><div className="brandmark"><ShieldCheck /></div><div><strong>SentinelOps</strong><small>Delivery Assurance</small></div></div>
      <nav aria-label="Principal">{nav.map(([id,label,Icon]) => <button key={id} className={page===id?'active':''} onClick={() => setPage(id)}><Icon size={19}/><span>{label}</span></button>)}</nav>
      <div className="sidebar-foot"><div className="control-plane"><span className="pulse"/>Control Plane conectado</div><button onClick={logout}><LogOut size={18}/>{t('logout')}</button></div>
    </aside>
    <main><header className="topbar"><div className="search"><Search size={18}/><span>Buscar serviços, traces, releases…</span><kbd>⌘ K</kbd></div><div className="tools"><button aria-label="Alternar idioma" onClick={() => { const next=i18n.language==='pt-BR'?'en-US':'pt-BR'; void i18n.changeLanguage(next);localStorage.setItem('sentinel-language',next) }}><Languages size={19}/></button><button aria-label="Alternar tema" onClick={() => setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={19}/>:<Moon size={19}/>}</button><div className="avatar">SR</div></div></header>
      <section className="content">{error&&<div className="error"><TriangleAlert size={18}/>{error}</div>}{loading&&<div className="loading">Atualizando sinais…</div>}
        {page==='overview'&&<Overview services={services} agents={agents} scenarios={scenarios} t={t}/>} {page==='catalog'&&<Catalog services={services}/>} {page==='tests'&&<TestStudio services={services} scenarios={scenarios} api={api} onSaved={s=>setScenarios(x=>[...x.filter(i=>i.name!==s.name),s])}/>} {page==='releases'&&<ReleaseView/>} {page==='agents'&&<Agents agents={agents}/>} {page==='help'&&<Help/>}
      </section>
    </main>
  </div>
}

function Login({api,oidc,onLogin}:{api:API;oidc:UserManager|null;onLogin:(token:string)=>void}) { const {t}=useTranslation(); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{const out=await api.login(String(f.get('username')),String(f.get('password')));onLogin(out.accessToken)}catch(err){setError(String(err))}finally{setBusy(false)}}
  return <div className="login-page"><div className="ambient one"/><div className="ambient two"/><form className="login-card" onSubmit={submit}><div className="brandmark large"><ShieldCheck/></div><p className="eyebrow">OBSERVABILITY · SYNTHETICS · DELIVERY</p><h1>{t('loginTitle')}</h1><p>{oidc?'Autentique-se pelo provedor OIDC corporativo.':<>Use a identidade local gerada por <code>make bootstrap</code>.</>}</p>{error&&<div className="error">{error}</div>}{oidc?<button type="button" className="primary" onClick={()=>void oidc.signinRedirect()}>Continuar com OIDC<ChevronRight size={18}/></button>:<><label>{t('username')}<input name="username" defaultValue="admin" autoComplete="username" required/></label><label>{t('password')}<input name="password" type="password" autoComplete="current-password" required/></label><button className="primary" disabled={busy}>{busy?'Autenticando…':t('login')}<ChevronRight size={18}/></button></>}<small>Sessão curta · MFA delegado ao provedor OIDC em produção</small></form></div>
}

function oidcManager():UserManager|null{const cfg=window.__SENTINEL_CONFIG__;if(cfg?.authMode!=='oidc'||!cfg.oidcAuthority||!cfg.oidcClientId)return null;return new UserManager({authority:cfg.oidcAuthority,client_id:cfg.oidcClientId,redirect_uri:location.origin+'/',post_logout_redirect_uri:location.origin+'/',response_type:'code',scope:cfg.oidcScope||'openid profile email',automaticSilentRenew:false})}

function Overview({services,agents,scenarios,t}:{services:Service[];agents:Agent[];scenarios:Scenario[];t:(k:string)=>string}) { const offline=agents.filter(a=>a.status==='offline').length
  return <><div className="page-head"><div><p className="eyebrow">SENTINEL CONTROL PLANE</p><h1>{t('welcome')}</h1><p>{t('subtitle')}</p></div><span className="time-range">Últimos 30 minutos</span></div>
    <div className="metrics"><Metric icon={CircleCheck} label={t('globalHealth')} value={offline?'Atenção':t('healthy')} tone={offline?'warn':'good'}/><Metric icon={Server} label={t('services')} value={String(services.length)} detail={`${services.length} monitorados`}/><Metric icon={TriangleAlert} label={t('degraded')} value="0" detail="sem regressões"/><Metric icon={RadioTower} label={t('offlineAgents')} value={String(offline)} tone={offline?'bad':'good'}/><Metric icon={Beaker} label={t('activeTests')} value={String(scenarios.filter(s=>s.enabled).length)} detail="agendados"/></div>
    <div className="grid two"><section className="panel"><PanelTitle icon={Activity} title="Pulso operacional" subtitle="Golden signals e entregas recentes"/><div className="spark"><svg viewBox="0 0 800 190" role="img" aria-label="Série temporal de disponibilidade"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#43e6bd" stopOpacity=".28"/><stop offset="1" stopColor="#43e6bd" stopOpacity="0"/></linearGradient></defs><path className="gridline" d="M0 45H800M0 95H800M0 145H800"/><path className="area" d="M0 140 C70 135 90 62 150 87 S250 155 310 84 S410 42 470 76 S560 132 630 70 S730 48 800 66 V190 H0Z"/><path className="line" d="M0 140 C70 135 90 62 150 87 S250 155 310 84 S410 42 470 76 S560 132 630 70 S730 48 800 66"/></svg><div className="chart-legend"><span><i/>Disponibilidade</span><b>99,97%</b></div></div></section>
      <section className="panel"><PanelTitle icon={Rocket} title="Confiança das entregas" subtitle="Resultado determinístico por release"/><div className="donut-row"><div className="donut"><span>96<small>/100</small></span></div><div className="checks"><Check label="Synthetic HTTP" value="PASS"/><Check label="Error rate" value="PASS"/><Check label="Latency p95" value="PASS"/><Check label="SLO burn rate" value="PASS"/></div></div></section></div></>
}
function Metric({icon:Icon,label,value,detail,tone=''}:{icon:typeof Gauge;label:string;value:string;detail?:string;tone?:string}){return <article className={`metric ${tone}`}><div className="metric-icon"><Icon size={20}/></div><p>{label}</p><strong>{value}</strong>{detail&&<small>{detail}</small>}</article>}
function PanelTitle({icon:Icon,title,subtitle}:{icon:typeof Gauge;title:string;subtitle:string}){return <div className="panel-title"><div><Icon size={19}/><h2>{title}</h2></div><p>{subtitle}</p></div>}
function Check({label,value}:{label:string;value:string}){return <div><span><CircleCheck size={16}/>{label}</span><b>{value}</b></div>}

function Catalog({services}:{services:Service[]}){const [q,setQ]=useState('');const shown=services.filter(s=>(s.displayName+s.name+s.ownerTeam).toLowerCase().includes(q.toLowerCase()));return <><div className="page-head"><div><p className="eyebrow">SERVICE CATALOG</p><h1>Serviços sob responsabilidade</h1><p>Owner, tier, telemetria e estado de entrega em um só contexto.</p></div></div><div className="filter"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Filtrar por nome, owner ou time"/></div><div className="service-list">{shown.map(s=><article key={s.id} className="service-card"><div className="service-avatar"><AppWindow/></div><div><h2>{s.displayName}</h2><code>{s.name}</code><p>{s.description||'Sem descrição operacional.'}</p></div><div className="service-meta"><span>Tier {s.tier}</span><span>{s.ownerTeam}</span><b><span className="status-dot"/> Saudável</b></div><ChevronRight/></article>)}{!shown.length&&<Empty text="Nenhum serviço cadastrado. Use sentinelctl service apply."/>}</div></>}

function TestStudio({services,scenarios,api,onSaved}:{services:Service[];scenarios:Scenario[];api:API;onSaved:(s:Scenario)=>void}){const [open,setOpen]=useState(false);const [message,setMessage]=useState('');async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const s=await api.saveScenario({name:String(f.get('name')),serviceRef:String(f.get('service')),environment:String(f.get('environment')),type:String(f.get('type')),spec:{url:String(f.get('url')),method:'GET',timeout:String(f.get('timeout')),assertions:[{field:'status',operator:'lessThan',value:400}],headers:{'X-Synthetic-Test':'sentinelops'}}});onSaved(s);setOpen(false);setMessage('Cenário publicado e versionado com sucesso.')}catch(err){setMessage(String(err))}}
  return <><div className="page-head"><div><p className="eyebrow">TEST STUDIO</p><h1>Testes que explicam a falha</h1><p>Crie sinais sintéticos seguros sem começar por código.</p></div><button className="primary compact" onClick={()=>setOpen(true)}><Beaker size={18}/>Novo cenário</button></div>{message&&<div className="notice">{message}</div>}<div className="scenario-grid">{scenarios.map(s=><article className="scenario-card" key={s.id}><div><span className="type">{s.type}</span><span className="version">v{s.version}</span></div><h2>{s.name}</h2><p>{s.serviceRef} · {s.environment}</p><div className="scenario-status"><span className="pulse"/>Agendamento ativo</div></article>)}{!scenarios.length&&<Empty text="Publique o primeiro cenário para iniciar o monitoramento sintético."/>}</div>{open&&<div className="modal-backdrop" onMouseDown={()=>setOpen(false)}><form className="modal" onSubmit={save} onMouseDown={e=>e.stopPropagation()}><p className="eyebrow">WIZARD · ETAPA ÚNICA</p><h2>Novo teste HTTP</h2><div className="form-grid"><Field label="Nome" help="Identificador DNS-safe. Ex.: api-health"><input name="name" required pattern="[a-z0-9][a-z0-9-]{1,62}"/></Field><Field label="Serviço" help="Associa evidências e ownership."><select name="service" required>{services.map(s=><option key={s.id} value={s.name}>{s.displayName}</option>)}</select></Field><Field label="Ambiente" help="Evita misturar baseline de DEV e PRD."><select name="environment"><option>development</option><option>staging</option><option>production</option></select></Field><Field label="Tipo" help="HTTP é leve; browser valida um fluxo real."><select name="type"><option value="http">HTTP</option><option value="browser">Browser</option><option value="k6">k6</option></select></Field><Field label="Endpoint" help="Alvo da execução. SSRF é validado no agente."><input name="url" type="url" required placeholder="https://app.example.com/health"/></Field><Field label="Timeout" help="Limite total; recomendado: 10s."><input name="timeout" defaultValue="10s" required/></Field></div><div className="modal-actions"><button type="button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary">Publicar cenário<ChevronRight size={18}/></button></div></form></div>}</>}
function Field({label,help,children}:{label:string;help:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}<small>{help}</small></label>}
function ReleaseView(){return <><div className="page-head"><div><p className="eyebrow">DELIVERY ASSURANCE</p><h1>Validação pós-deploy</h1><p>Checks versionados; ausência de evidência nunca vira sucesso.</p></div></div><section className="panel timeline"><div className="timeline-step done"><CircleCheck/><div><b>Release registrada</b><small>imagem, digest e commit vinculados</small></div><time>00:00</time></div><div className="timeline-step done"><CircleCheck/><div><b>Aplicação estabilizada</b><small>janela de 2 minutos concluída</small></div><time>02:00</time></div><div className="timeline-step current"><Activity/><div><b>Checks determinísticos</b><small>synthetics, métricas, logs, traces e SLO</small></div><time>em execução</time></div><div className="timeline-step"><CircleCheck/><div><b>Resultado do gate</b><small>PASS · WARN · FAIL · INCONCLUSIVE</small></div></div></section></>}
function Agents({agents}:{agents:Agent[]}){return <><div className="page-head"><div><p className="eyebrow">AGENT FLEET</p><h1>Execução onde o sistema vive</h1><p>Localidade, capabilities e heartbeat sem abrir a rede privada.</p></div></div><div className="agent-table"><div className="table-head"><span>Agente</span><span>Localidade</span><span>Ambiente</span><span>Heartbeat</span><span>Status</span></div>{agents.map(a=><div className="table-row" key={a.id}><b>{a.name}</b><span>{a.location||a.region}</span><span>{a.environment}</span><span>{a.lastHeartbeat?new Date(a.lastHeartbeat).toLocaleString():'Nunca'}</span><strong className={a.status}><i/>{a.status}</strong></div>)}{!agents.length&&<Empty text="Nenhum agente registrado."/>}</div></>}
function Help(){return <><div className="page-head"><div><p className="eyebrow">OBSERVABILITY BASICS</p><h1>Decida sem decorar jargões</h1><p>Definições curtas conectadas ao impacto operacional.</p></div></div><div className="glossary">{glossary.map(([term,definition])=><article key={term}><div className="glossary-icon"><BookOpen/></div><h2>{term}</h2><p>{definition}</p><a href="https://sre.google/sre-book/service-level-objectives/" target="_blank" rel="noreferrer">Ver contexto <ChevronRight size={15}/></a></article>)}</div></>}
function Empty({text}:{text:string}){return <div className="empty"><Boxes/><p>{text}</p></div>}
