import { useEffect, useMemo, useState } from 'react'
import { Activity, Box, Boxes, ChevronRight, Container, Cpu, Database, FileText, Gauge, MemoryStick, Search, TriangleAlert, Waves } from 'lucide-react'
import { API, APMService, ContainerDetails, ContainerSummary, HostDetails, HostSummary, LogEntry, SourceStatus, TelemetrySeries, TraceSummary } from './api'

export type ObservabilityPage = 'hosts' | 'docker' | 'logs' | 'metrics' | 'apm' | 'traces' | 'profiles'
export type EntityContext = { host?: string; container?: string; containerId?: string; service?: string }

export function ObservabilityView({ page, api, context, onContext, onPage }: { page: ObservabilityPage; api: API; context: EntityContext; onContext: (value: EntityContext) => void; onPage: (page: ObservabilityPage) => void }) {
  if (page === 'hosts') return <HostsPage api={api} context={context} onContext={onContext} onPage={onPage}/>
  if (page === 'docker') return <DockerPage api={api} context={context} onContext={onContext} onPage={onPage}/>
  if (page === 'logs') return <LogsPage api={api} context={context}/>
  if (page === 'apm') return <APMPage api={api} onContext={onContext} onPage={onPage}/>
  if (page === 'traces') return <TracesPage api={api} context={context}/>
  if (page === 'metrics') return <MetricsPage api={api} context={context} onPage={onPage}/>
  return <ProfilesPage context={context}/>
}

function HostsPage({ api, context, onContext, onPage }: { api: API; context: EntityContext; onContext: (value: EntityContext) => void; onPage: (page: ObservabilityPage) => void }) {
  const [hosts, setHosts] = useState<HostSummary[]>([]); const [source, setSource] = useState<SourceStatus>(); const [selected, setSelected] = useState(context.host || ''); const [details, setDetails] = useState<HostDetails>(); const [window, setWindow] = useState('1h'); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { let active = true; setLoading(true); api.hosts().then(result => { if (active) { setHosts(result.items); setSource(result.sources.prometheus); if (!selected && result.items.length) setSelected(result.items[0].instance); setError('') } }).catch(e => active && setError(String(e))).finally(() => active && setLoading(false)); return () => { active = false } }, [api])
  useEffect(() => { if (!selected) { setDetails(undefined); return }; let active = true; api.hostDetails(selected, window).then(result => active && setDetails(result)).catch(e => active && setError(String(e))); return () => { active = false } }, [api, selected, window])
  const host = hosts.find(item => item.instance === selected)
  function choose(value: HostSummary) { setSelected(value.instance); onContext({ host: value.instance }) }
  return <><PageHead eyebrow="INFRASTRUCTURE / HOSTS" title="Hosts observados" subtitle="Inventário vivo e sinais do node_exporter; ausência de série permanece Sem dados."/><SourceBanner source={source} loading={loading}/>{error && <ErrorBanner text={error}/>}<div className="obs-layout"><section className="obs-list"><div className="obs-list-head"><b>{hosts.length} hosts</b><span>Prometheus / Mimir</span></div>{hosts.map(item => <button key={item.instance} className={selected === item.instance ? 'selected' : ''} onClick={() => choose(item)}><Status state={item.state}/><div><strong>{item.name}</strong><small>{item.instance} · {item.environment || 'ambiente sem label'}</small></div><TelemetryValue value={item.cpuPercent} suffix="% CPU"/><ChevronRight size={17}/></button>)}{!loading && hosts.length === 0 && <NoData text="Nenhum host com node_uname_info ou up{job=linux-node}."/>}</section><section className="obs-detail">{host && details ? <><div className="entity-head"><div><p className="eyebrow">HOST DETAILS</p><h2>{host.name}</h2><span>{host.os || 'OS Sem dados'} · {host.kernel || 'kernel Sem dados'} · {host.architecture || 'arquitetura Sem dados'}</span></div><TimeRange value={window} onChange={setWindow}/></div><div className="entity-actions"><button onClick={() => onPage('metrics')}><Gauge size={16}/>Métricas</button><button onClick={() => onPage('logs')}><FileText size={16}/>Logs</button><button onClick={() => onPage('docker')}><Container size={16}/>Containers</button></div><div className="signal-grid"><Signal icon={Cpu} label="CPU" value={formatPercent(host.cpuPercent)} tone={thresholdTone(host.cpuPercent)}/><Signal icon={MemoryStick} label="Memória" value={formatPercent(host.memoryPercent)} tone={thresholdTone(host.memoryPercent)}/><Signal icon={Database} label="Filesystem máx." value={formatPercent(host.diskPercent)} tone={thresholdTone(host.diskPercent)}/><Signal icon={Activity} label="Estado" value={host.state}/></div><ChartGrid metrics={details.metrics} preferred={['cpuByMode', 'memoryUsed', 'diskUsed', 'networkRx', 'networkTx', 'load1']}/></> : <NoData text="Selecione um host para abrir CPU, memória, disco e rede."/>}</section></div></>
}

function DockerPage({ api, context, onContext, onPage }: { api: API; context: EntityContext; onContext: (value: EntityContext) => void; onPage: (page: ObservabilityPage) => void }) {
  const [items, setItems] = useState<ContainerSummary[]>([]); const [source, setSource] = useState<SourceStatus>(); const [selected, setSelected] = useState(context.container || ''); const [host, setHost] = useState(context.host || ''); const [details, setDetails] = useState<ContainerDetails>(); const [window, setWindow] = useState('1h'); const [query, setQuery] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { let active = true; setLoading(true); api.containers(context.host ? { host: context.host } : {}).then(result => { if (active) { setItems(result.items); setSource(result.sources.prometheus); if (!selected && result.items.length) { setSelected(result.items[0].name); setHost(result.items[0].host) }; setError('') } }).catch(e => active && setError(String(e))).finally(() => active && setLoading(false)); return () => { active = false } }, [api, context.host])
  useEffect(() => { if (!selected) { setDetails(undefined); return }; let active = true; api.containerDetails(selected, host, window).then(result => active && setDetails(result)).catch(e => active && setError(String(e))); return () => { active = false } }, [api, selected, host, window])
  const shown = useMemo(() => items.filter(item => (item.name + item.image + item.host + item.service).toLowerCase().includes(query.toLowerCase())), [items, query]); const item = items.find(value => value.name === selected && value.host === host)
  function choose(value: ContainerSummary) { setSelected(value.name); setHost(value.host); onContext({ host: value.host, container: value.name, containerId: shortContainerID(value.id), service: value.service }) }
  return <><PageHead eyebrow="INFRASTRUCTURE / DOCKER" title="Containers Docker" subtitle="Métricas cAdvisor correlacionadas por host e identidade do container."/><SourceBanner source={source} loading={loading}/>{error && <ErrorBanner text={error}/>}<div className="filter obs-filter"><Search size={17}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Filtrar host, container, image ou service"/></div><div className="obs-layout"><section className="obs-list"><div className="obs-list-head"><b>{shown.length} containers</b><span>cAdvisor</span></div>{shown.map(value => <button key={`${value.host}/${value.name}`} className={selected === value.name && host === value.host ? 'selected' : ''} onClick={() => choose(value)}><Status state={value.state}/><div><strong>{value.name}</strong><small>{value.host} · {value.image || 'imagem Sem dados'}</small></div><TelemetryValue value={value.cpuPercent} suffix="% CPU"/><ChevronRight size={17}/></button>)}{!loading && shown.length === 0 && <NoData text="Nenhum container_last_seen corresponde ao filtro."/>}</section><section className="obs-detail">{item && details ? <><div className="entity-head"><div><p className="eyebrow">CONTAINER DETAILS</p><h2>{item.name}</h2><span>{item.image || 'imagem Sem dados'} · {item.host}</span></div><TimeRange value={window} onChange={setWindow}/></div><div className="entity-actions"><button onClick={() => onPage('logs')}><FileText size={16}/>Logs</button><button onClick={() => onPage('traces')}><Waves size={16}/>Traces</button><button onClick={() => onPage('metrics')}><Gauge size={16}/>Métricas</button></div><div className="signal-grid"><Signal icon={Cpu} label="CPU" value={formatPercent(item.cpuPercent)} tone={thresholdTone(item.cpuPercent)}/><Signal icon={MemoryStick} label="Memória" value={formatBytes(item.memoryBytes)}/><Signal icon={Activity} label="Restarts 24h" value={formatNumber(item.restarts24h)}/><Signal icon={Box} label="Service" value={item.service || 'Sem dados'}/></div><ChartGrid metrics={details.metrics} preferred={['cpu', 'throttling', 'memory', 'networkRx', 'networkTx', 'filesystem']}/></> : <NoData text="Selecione um container para abrir recursos e correlação."/>}</section></div></>
}

function LogsPage({ api, context }: { api: API; context: EntityContext }) {
  const [entries, setEntries] = useState<LogEntry[]>([]); const [source, setSource] = useState<SourceStatus>(); const [severity, setSeverity] = useState(''); const [search, setSearch] = useState(''); const [window, setWindow] = useState('15m'); const [nonce, setNonce] = useState(0); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  useEffect(() => { let active = true; setLoading(true); api.logs({ host: context.host, containerId: context.containerId, service: context.service, severity, search, window, limit: 300 }).then(result => { if (active) { setEntries(result.items); setSource(result.sources.loki); setError('') } }).catch(e => active && setError(String(e))).finally(() => active && setLoading(false)); return () => { active = false } }, [api, context.host, context.containerId, context.service, severity, search, window, nonce])
  return <><PageHead eyebrow="OBSERVE / LOGS" title="Log Explorer" subtitle="Loki com filtros de contexto; o evento original permanece intacto."/><div className="context-strip"><ContextChip label="Host" value={context.host}/><ContextChip label="Container" value={context.container}/><ContextChip label="Service" value={context.service}/></div><div className="querybar"><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Buscar texto literal"/><select value={severity} onChange={event => setSeverity(event.target.value)}><option value="">Todas severidades</option><option>ERROR</option><option>WARN</option><option>INFO</option><option>DEBUG</option></select><TimeRange value={window} onChange={setWindow}/><button onClick={() => setNonce(value => value + 1)}>Atualizar</button></div><SourceBanner source={source} loading={loading}/>{error && <ErrorBanner text={error}/>}<div className="log-table">{entries.map((entry, index) => <article key={`${entry.timestamp}-${index}`}><time>{new Date(entry.timestamp).toLocaleString('pt-BR')}</time><span className={severityClass(entry)}>{inferSeverity(entry)}</span><div><b>{entry.labels.service_name || entry.labels.container_name || entry.labels.container_id || entry.labels.host_name || 'origem Sem dados'}</b><pre>{entry.line}</pre></div></article>)}{!loading && entries.length === 0 && <NoData text="Nenhum evento na janela e no contexto selecionados."/>}</div></>
}

function APMPage({ api, onContext, onPage }: { api: API; onContext: (value: EntityContext) => void; onPage: (page: ObservabilityPage) => void }) {
  const [items, setItems] = useState<APMService[]>([]); const [source, setSource] = useState<SourceStatus>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { let active = true; api.apm().then(result => { if (active) { setItems(result.items); setSource(result.sources.prometheus) } }).catch(e => active && setError(String(e))).finally(() => active && setLoading(false)); return () => { active = false } }, [api])
  function open(item: APMService) { onContext({ service: item.name, host: item.host }); onPage('traces') }
  return <><PageHead eyebrow="OBSERVE / APM" title="Application Performance" subtitle="RED e percentis derivados de métricas OpenTelemetry reais."/><SourceBanner source={source} loading={loading}/>{error && <ErrorBanner text={error}/>}<div className="apm-table"><div className="apm-row header"><span>Service</span><span>Rate</span><span>Errors</span><span>p95</span><span>p99</span><span/></div>{items.map(item => <button className="apm-row" key={item.name} onClick={() => open(item)}><span><b>{item.name}</b><small>{item.environment || 'ambiente Sem dados'} · {item.host || 'host Sem dados'}</small></span><TelemetryValue value={item.requestsPerSecond} suffix=" req/s"/><TelemetryValue value={item.errorPercent} suffix="%"/><TelemetryValue value={secondsToMs(item.p95Seconds)} suffix=" ms"/><TelemetryValue value={secondsToMs(item.p99Seconds)} suffix=" ms"/><ChevronRight size={17}/></button>)}{!loading && items.length === 0 && <NoData text="Nenhuma série http_server_request_duration_seconds com service_name."/>}</div></>
}

function TracesPage({ api, context }: { api: API; context: EntityContext }) {
  const [items, setItems] = useState<TraceSummary[]>([]); const [source, setSource] = useState<SourceStatus>(); const [errorOnly, setErrorOnly] = useState(false); const [window, setWindow] = useState('1h'); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { let active = true; setLoading(true); api.traces({ host: context.host, container: context.container, service: context.service, error: errorOnly, window }).then(result => { if (active) { setItems(result.items); setSource(result.sources.tempo); setError('') } }).catch(e => active && setError(String(e))).finally(() => active && setLoading(false)); return () => { active = false } }, [api, context.host, context.container, context.service, errorOnly, window])
  return <><PageHead eyebrow="OBSERVE / TRACES" title="Distributed Tracing" subtitle="Busca TraceQL preservando service, container e host selecionados."/><div className="context-strip"><ContextChip label="Host" value={context.host}/><ContextChip label="Container" value={context.container}/><ContextChip label="Service" value={context.service}/><label className="check"><input type="checkbox" checked={errorOnly} onChange={event => setErrorOnly(event.target.checked)}/>Somente erros</label><TimeRange value={window} onChange={setWindow}/></div><SourceBanner source={source} loading={loading}/>{error && <ErrorBanner text={error}/>}<div className="trace-list">{items.map(item => <article key={item.traceId}><Waves/><div><b>{item.rootServiceName || 'service Sem dados'}</b><span>{item.rootTraceName || 'operação Sem dados'}</span><code>{item.traceId}</code></div><strong>{item.durationMs.toFixed(1)} ms</strong></article>)}{!loading && items.length === 0 && <NoData text="Nenhum trace corresponde ao contexto e à janela."/>}</div></>
}

function MetricsPage({ api, context, onPage }: { api: API; context: EntityContext; onPage: (page: ObservabilityPage) => void }) {
  const [details, setDetails] = useState<HostDetails>(); const [window, setWindow] = useState('1h'); const [error, setError] = useState('')
  useEffect(() => { if (!context.host) return; let active = true; api.hostDetails(context.host, window).then(value => active && setDetails(value)).catch(e => active && setError(String(e))); return () => { active = false } }, [api, context.host, window])
  return <><PageHead eyebrow="OBSERVE / METRICS" title="Metrics Explorer" subtitle="Visões operacionais prontas; PromQL arbitrário não é exposto ao navegador."/>{error && <ErrorBanner text={error}/>}<div className="context-strip"><ContextChip label="Host" value={context.host}/><ContextChip label="Container" value={context.container}/><ContextChip label="Service" value={context.service}/><TimeRange value={window} onChange={setWindow}/></div>{context.host && details ? <><SourceBanner source={details.sources.prometheus}/><ChartGrid metrics={details.metrics} preferred={Object.keys(details.metrics)}/></> : <NoData text="Selecione um host em Infrastructure → Hosts para preservar o contexto das métricas."/>}<button className="link-button" onClick={() => onPage('hosts')}>Abrir Hosts</button></>
}

function ProfilesPage({ context }: { context: EntityContext }) {
  return <><PageHead eyebrow="OBSERVE / PROFILES" title="Continuous Profiling" subtitle="O contexto da entidade é preservado para CPU, memória, allocations e wall time."/><div className="context-strip"><ContextChip label="Host" value={context.host}/><ContextChip label="Container" value={context.container}/><ContextChip label="Service" value={context.service}/></div><div className="source-banner no_data"><Gauge/><div><b>Metric unsupported na experiência nativa atual</b><span>Pyroscope recebe profiles no Data Plane, mas o Control Plane ainda não possui uma rota allowlisted para consultar e renderizar flamegraphs. Nenhum perfil é inventado.</span></div></div></>
}

function PageHead({ eyebrow, title, subtitle }: { eyebrow: string; title: string; subtitle: string }) { return <div className="page-head"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{subtitle}</p></div></div> }
function SourceBanner({ source, loading = false }: { source?: SourceStatus; loading?: boolean }) { if (loading) return <div className="source-banner loading-inline"><Activity/><div><b>Consultando fonte real</b><span>Aguardando resposta do backend.</span></div></div>; if (!source) return null; return <div className={`source-banner ${source.state}`}><Database/><div><b>{source.state === 'available' ? 'Telemetria disponível' : source.state === 'partial' ? 'Telemetria parcial' : source.state === 'no_data' ? 'Sem dados' : 'Telemetry unavailable'}</b><span>{source.message || `Fonte consultada em ${new Date(source.fetchedAt).toLocaleString('pt-BR')}`}</span></div></div> }
function ErrorBanner({ text }: { text: string }) { return <div className="error"><TriangleAlert size={17}/>{text}</div> }
function NoData({ text }: { text: string }) { return <div className="empty obs-empty"><Boxes/><p>{text}</p></div> }
function Status({ state }: { state: string }) { return <i className={`entity-status ${state}`} title={state}/> }
function ContextChip({ label, value }: { label: string; value?: string }) { return <span className={value ? 'context-chip' : 'context-chip empty'}><small>{label}</small>{value || 'Todos'}</span> }
function TelemetryValue({ value, suffix }: { value: number | null | undefined; suffix: string }) { return <span className="telemetry-value">{value == null ? 'Sem dados' : `${value.toFixed(value >= 100 ? 0 : 1)}${suffix}`}</span> }
function Signal({ icon: Icon, label, value, tone = '' }: { icon: typeof Gauge; label: string; value: string; tone?: string }) { return <article className={`signal ${tone}`}><Icon/><span>{label}</span><strong>{value}</strong></article> }
function TimeRange({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <select className="time-select" value={value} onChange={event => onChange(event.target.value)}><option value="15m">15m</option><option value="1h">1h</option><option value="6h">6h</option><option value="24h">24h</option></select> }

function ChartGrid({ metrics, preferred }: { metrics: Record<string, TelemetrySeries[]>; preferred: string[] }) { return <div className="chart-grid">{preferred.map(name => <MiniChart key={name} title={metricTitle(name)} series={metrics[name] || []}/>)}</div> }
function MiniChart({ title, series }: { title: string; series: TelemetrySeries[] }) {
  const points = series.flatMap(item => item.points.map(point => point.value)).filter(Number.isFinite); const min = points.length ? Math.min(...points) : 0; const max = points.length ? Math.max(...points) : 0
  return <article className="mini-chart"><header><b>{title}</b><span>{points.length ? `${formatCompact(points.at(-1)!)} atual` : 'Sem dados'}</span></header>{points.length ? <svg viewBox="0 0 320 92" preserveAspectRatio="none" role="img" aria-label={`${title}: ${points.length} amostras`}><polyline points={points.map((value, index) => `${(index / Math.max(points.length - 1, 1)) * 320},${86 - ((value - min) / Math.max(max - min, 1)) * 76}`).join(' ')}/></svg> : <div className="chart-no-data">No data</div>}<footer><span>{series.length} séries</span><span>{formatCompact(min)} — {formatCompact(max)}</span></footer></article>
}

function metricTitle(name: string) { const labels: Record<string, string> = { cpuByMode: 'CPU por modo', load1: 'Load average 1m', load5: 'Load average 5m', load15: 'Load average 15m', memoryUsed: 'Memória utilizada %', swapUsed: 'Swap utilizada %', diskUsed: 'Filesystem utilizado %', diskRead: 'Disk read bytes/s', diskWrite: 'Disk write bytes/s', networkRx: 'Network RX bytes/s', networkTx: 'Network TX bytes/s', cpu: 'CPU %', throttling: 'CPU throttling %', memory: 'Memory working set', memoryLimit: 'Memory limit', filesystem: 'Filesystem I/O' }; return labels[name] || name }
function formatPercent(value: number | null) { return value == null ? 'Sem dados' : `${value.toFixed(1)}%` }
function formatNumber(value: number | null) { return value == null ? 'Sem dados' : value.toFixed(0) }
function formatBytes(value: number | null) { if (value == null) return 'Sem dados'; const units = ['B', 'KiB', 'MiB', 'GiB', 'TiB']; let current = value; let unit = 0; while (current >= 1024 && unit < units.length - 1) { current /= 1024; unit++ }; return `${current.toFixed(current >= 100 ? 0 : 1)} ${units[unit]}` }
function formatCompact(value: number) { return new Intl.NumberFormat('pt-BR', { notation: 'compact', maximumFractionDigits: 1 }).format(value) }
function thresholdTone(value: number | null) { return value == null ? '' : value >= 90 ? 'bad' : value >= 80 ? 'warn' : 'good' }
function secondsToMs(value: number | null) { return value == null ? null : value * 1000 }
function shortContainerID(value?: string) { if (!value) return undefined; const segments = value.split('/').filter(Boolean); return (segments.at(-1) || value).slice(0, 64) }
function inferSeverity(entry: LogEntry) { const explicit = (entry.labels.severity || entry.labels.level || '').toUpperCase(); if (explicit) return explicit; if (/fatal|error|exception/i.test(entry.line)) return 'ERROR'; if (/warn/i.test(entry.line)) return 'WARN'; if (/debug/i.test(entry.line)) return 'DEBUG'; return 'INFO' }
function severityClass(entry: LogEntry) { return `log-severity ${inferSeverity(entry).toLowerCase()}` }
