api:
  replicas: 5
  autoscaling: { enabled: true, minReplicas: 5, maxReplicas: 30, targetCPUUtilizationPercentage: 65 }
  resources: { requests: { cpu: 500m, memory: 512Mi }, limits: { cpu: "2", memory: 2Gi } }
worker:
  replicas: 5
  resources: { requests: { cpu: 500m, memory: 512Mi }, limits: { cpu: "2", memory: 2Gi } }
web: { replicas: 3 }
agent: { enabled: false }

