resolver 127.0.0.11 valid=1s ipv6=off;

upstream sentinel_api_ha {
  zone sentinel_api_ha 64k;
  server api:8080 resolve max_fails=1 fail_timeout=1s;
}

server {
  listen 3000;
  server_name _;
  server_tokens off;

  proxy_connect_timeout 500ms;
  proxy_read_timeout 30s;
  proxy_next_upstream error timeout http_502 http_503 http_504;
  proxy_next_upstream_tries 3;

  location / {
    proxy_pass http://sentinel_api_ha;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Request-ID $request_id;
  }
}
